repos:
- repo: local
  hooks:
    - id: linters
      name: Run linters
      types_or: [go]
      pass_filenames: false
      language: system
      entry: task lint
      stages:
        - pre-push

    - id: tests
      name: Run tests
      types_or: [go]
      pass_filenames: false
      language: system
      entry: task test
      stages:
        - pre-push
